var languageNamespace ={
    'en': 'English',
    'nl': 'Dutch',
    'es': 'Espanol',
    'fr': 'Francais',
    'it': 'Italiano',
    'de': 'German',
    //'ru': 'Russian',
    //'ja': 'Japanese',
    'pl': 'Polski',
    'pt': 'Portugues',
    'sv': 'Svenska',
    //'ar': 'Arabic',
    //'fa': 'Farsi',
    //'he': 'Hebrew' ,
    //'id': 'Indonesian',
    //'zh': 'Chinese',
    //'as': 'Assamese',
    //'hi': 'Hindi', 
    //'bn': 'Bengali',
    //'pa': 'Punjabi',
    //'te': 'Telugu',
    //'ta': 'Tamil', 
    //'ml': 'Malayalam',
    //'mr': 'Western Mari',
    //'kn': 'Kannada',
    //'or': 'Oriya',
    //'sa': 'Sanskrit', 
    //'gu': 'Gujarati' ,
}