var languageNamespace ={
    'en': 'English',
    'nl': 'Dutch',
    'es': 'Español',
    'fr': 'Français',
    'it': 'Italiano',
    'de': 'Deutsch',
    'ru': 'Русский',
    //'ja': 'Japanese',
    'pl': 'Polski',
    'pt': 'Português',
    'sv': 'Svenska',
    'fi': 'Suomi',
    'ca': 'Català',
    'war': 'Winaray',
    'ro': 'Română',
    'eo': 'Esperanto',
    'da': 'Dansk',
    'sk': 'Slovenčina',
    'tr': 'Türkçe',
    'ms': 'Bahasa Melayu',
    'simple': 'Simple English',
    //'ar': 'Arabic',
    //'fa': 'Farsi',
    //'he': 'Hebrew' ,
    //'id': 'Indonesian',
    //'zh': 'Chinese',
    //'as': 'Assamese',
    //'hi': 'Hindi', 
    //'bn': 'Bengali',
    //'pa': 'Punjabi',
    //'te': 'Telugu',
    //'ta': 'Tamil', 
    //'ml': 'Malayalam',
    //'mr': 'Western Mari',
    //'kn': 'Kannada',
    //'or': 'Oriya',
    //'sa': 'Sanskrit', 
    //'gu': 'Gujarati' ,
}
